# Generated by Django 3.0.5 on 2020-04-20 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0006_auto_20200420_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('short_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.ShortURL')),
            ],
        ),
    ]
