# Generated by Django 3.0.5 on 2020-04-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='shortcode',
            field=models.CharField(default=123, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shorturl',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
