# Generated by Django 3.0.5 on 2020-04-20 02:43

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_shorturl_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='url',
            field=models.CharField(max_length=220, validators=[app.validators.validate_url, app.validators.validate_dot_com]),
        ),
    ]
