# Generated by Django 3.0.5 on 2020-04-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200420_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
